version: "2"

run:
    timeout: 5m
    tests: false
    issues-exit-code: 1

formatters:
    enable:
        - gofumpt
        - goimports

linters:
    enable:
        - govet
        - staticcheck
        - errcheck
        - unused
        - ineffassign
        - lll
        - gocyclo
        - gocognit
        - goconst

    exclusions:
        paths:
            - vendor
            - third_party
            - mocks
            - scripts
            - tools

    settings:
        gocognit:
            min-complexity: 500

        gocyclo:
            min-complexity: 500

        errcheck:
            check-type-assertions: true
            check-blank: true

        staticcheck:
            checks:
                - all
                - "-ST1000"
                - "-ST1003"

        lll:
            line-length: 130
            tab-width: 4

output:
    formats:
        tab: {}
