// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ledger_service/service.proto

package ledger_servicev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Category with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Category) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Category with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CategoryMultiError, or nil
// if none found.
func (m *Category) ValidateAll() error {
	return m.validate(true)
}

func (m *Category) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	if len(errors) > 0 {
		return CategoryMultiError(errors)
	}

	return nil
}

// CategoryMultiError is an error wrapping multiple validation errors returned
// by Category.ValidateAll() if the designated constraints aren't met.
type CategoryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CategoryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CategoryMultiError) AllErrors() []error { return m }

// CategoryValidationError is the validation error returned by
// Category.Validate if the designated constraints aren't met.
type CategoryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CategoryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CategoryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CategoryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CategoryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CategoryValidationError) ErrorName() string { return "CategoryValidationError" }

// Error satisfies the builtin error interface
func (e CategoryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCategory.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CategoryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CategoryValidationError{}

// Validate checks the field values on Date with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Date) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Date with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DateMultiError, or nil if none found.
func (m *Date) ValidateAll() error {
	return m.validate(true)
}

func (m *Date) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Year

	// no validation rules for Month

	// no validation rules for Day

	if len(errors) > 0 {
		return DateMultiError(errors)
	}

	return nil
}

// DateMultiError is an error wrapping multiple validation errors returned by
// Date.ValidateAll() if the designated constraints aren't met.
type DateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DateMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DateMultiError) AllErrors() []error { return m }

// DateValidationError is the validation error returned by Date.Validate if the
// designated constraints aren't met.
type DateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DateValidationError) ErrorName() string { return "DateValidationError" }

// Error satisfies the builtin error interface
func (e DateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DateValidationError{}

// Validate checks the field values on DateMonth with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DateMonth) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DateMonth with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DateMonthMultiError, or nil
// if none found.
func (m *DateMonth) ValidateAll() error {
	return m.validate(true)
}

func (m *DateMonth) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Year

	// no validation rules for Month

	if len(errors) > 0 {
		return DateMonthMultiError(errors)
	}

	return nil
}

// DateMonthMultiError is an error wrapping multiple validation errors returned
// by DateMonth.ValidateAll() if the designated constraints aren't met.
type DateMonthMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DateMonthMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DateMonthMultiError) AllErrors() []error { return m }

// DateMonthValidationError is the validation error returned by
// DateMonth.Validate if the designated constraints aren't met.
type DateMonthValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DateMonthValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DateMonthValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DateMonthValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DateMonthValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DateMonthValidationError) ErrorName() string { return "DateMonthValidationError" }

// Error satisfies the builtin error interface
func (e DateMonthValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDateMonth.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DateMonthValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DateMonthValidationError{}

// Validate checks the field values on Transaction with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Transaction) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Transaction with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TransactionMultiError, or
// nil if none found.
func (m *Transaction) ValidateAll() error {
	return m.validate(true)
}

func (m *Transaction) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for AccountId

	// no validation rules for IsIncome

	// no validation rules for Amount

	if all {
		switch v := interface{}(m.GetOccurredOn()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TransactionValidationError{
					field:  "OccurredOn",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TransactionValidationError{
					field:  "OccurredOn",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOccurredOn()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransactionValidationError{
				field:  "OccurredOn",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CategoryId

	// no validation rules for Description

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TransactionValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TransactionValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransactionValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TransactionValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TransactionValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransactionValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TransactionMultiError(errors)
	}

	return nil
}

// TransactionMultiError is an error wrapping multiple validation errors
// returned by Transaction.ValidateAll() if the designated constraints aren't met.
type TransactionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransactionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransactionMultiError) AllErrors() []error { return m }

// TransactionValidationError is the validation error returned by
// Transaction.Validate if the designated constraints aren't met.
type TransactionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransactionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransactionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransactionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransactionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransactionValidationError) ErrorName() string { return "TransactionValidationError" }

// Error satisfies the builtin error interface
func (e TransactionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransaction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransactionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransactionValidationError{}

// Validate checks the field values on Budget with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Budget) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Budget with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BudgetMultiError, or nil if none found.
func (m *Budget) ValidateAll() error {
	return m.validate(true)
}

func (m *Budget) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for AccountId

	if all {
		switch v := interface{}(m.GetPeriod()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BudgetValidationError{
					field:  "Period",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BudgetValidationError{
					field:  "Period",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPeriod()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BudgetValidationError{
				field:  "Period",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CategoryId

	// no validation rules for Amount

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BudgetValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BudgetValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BudgetValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BudgetValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BudgetValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BudgetValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BudgetMultiError(errors)
	}

	return nil
}

// BudgetMultiError is an error wrapping multiple validation errors returned by
// Budget.ValidateAll() if the designated constraints aren't met.
type BudgetMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BudgetMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BudgetMultiError) AllErrors() []error { return m }

// BudgetValidationError is the validation error returned by Budget.Validate if
// the designated constraints aren't met.
type BudgetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BudgetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BudgetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BudgetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BudgetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BudgetValidationError) ErrorName() string { return "BudgetValidationError" }

// Error satisfies the builtin error interface
func (e BudgetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBudget.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BudgetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BudgetValidationError{}

// Validate checks the field values on ListCategoriesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListCategoriesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListCategoriesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListCategoriesRequestMultiError, or nil if none found.
func (m *ListCategoriesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListCategoriesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListCategoriesRequestMultiError(errors)
	}

	return nil
}

// ListCategoriesRequestMultiError is an error wrapping multiple validation
// errors returned by ListCategoriesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListCategoriesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListCategoriesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListCategoriesRequestMultiError) AllErrors() []error { return m }

// ListCategoriesRequestValidationError is the validation error returned by
// ListCategoriesRequest.Validate if the designated constraints aren't met.
type ListCategoriesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCategoriesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCategoriesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCategoriesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCategoriesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCategoriesRequestValidationError) ErrorName() string {
	return "ListCategoriesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListCategoriesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCategoriesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCategoriesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCategoriesRequestValidationError{}

// Validate checks the field values on ListCategoriesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListCategoriesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListCategoriesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListCategoriesResponseMultiError, or nil if none found.
func (m *ListCategoriesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListCategoriesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListCategoriesResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListCategoriesResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListCategoriesResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListCategoriesResponseMultiError(errors)
	}

	return nil
}

// ListCategoriesResponseMultiError is an error wrapping multiple validation
// errors returned by ListCategoriesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListCategoriesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListCategoriesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListCategoriesResponseMultiError) AllErrors() []error { return m }

// ListCategoriesResponseValidationError is the validation error returned by
// ListCategoriesResponse.Validate if the designated constraints aren't met.
type ListCategoriesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCategoriesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCategoriesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCategoriesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCategoriesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCategoriesResponseValidationError) ErrorName() string {
	return "ListCategoriesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListCategoriesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCategoriesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCategoriesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCategoriesResponseValidationError{}

// Validate checks the field values on AddTransactionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddTransactionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddTransactionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddTransactionRequestMultiError, or nil if none found.
func (m *AddTransactionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddTransactionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsIncome

	// no validation rules for Amount

	if all {
		switch v := interface{}(m.GetOccurredOn()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AddTransactionRequestValidationError{
					field:  "OccurredOn",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AddTransactionRequestValidationError{
					field:  "OccurredOn",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOccurredOn()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AddTransactionRequestValidationError{
				field:  "OccurredOn",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CategoryId

	// no validation rules for Description

	if len(errors) > 0 {
		return AddTransactionRequestMultiError(errors)
	}

	return nil
}

// AddTransactionRequestMultiError is an error wrapping multiple validation
// errors returned by AddTransactionRequest.ValidateAll() if the designated
// constraints aren't met.
type AddTransactionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddTransactionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddTransactionRequestMultiError) AllErrors() []error { return m }

// AddTransactionRequestValidationError is the validation error returned by
// AddTransactionRequest.Validate if the designated constraints aren't met.
type AddTransactionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddTransactionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddTransactionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddTransactionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddTransactionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddTransactionRequestValidationError) ErrorName() string {
	return "AddTransactionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AddTransactionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddTransactionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddTransactionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddTransactionRequestValidationError{}

// Validate checks the field values on AddTransactionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddTransactionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddTransactionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddTransactionResponseMultiError, or nil if none found.
func (m *AddTransactionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddTransactionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AddTransactionResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AddTransactionResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AddTransactionResponseValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AddTransactionResponseMultiError(errors)
	}

	return nil
}

// AddTransactionResponseMultiError is an error wrapping multiple validation
// errors returned by AddTransactionResponse.ValidateAll() if the designated
// constraints aren't met.
type AddTransactionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddTransactionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddTransactionResponseMultiError) AllErrors() []error { return m }

// AddTransactionResponseValidationError is the validation error returned by
// AddTransactionResponse.Validate if the designated constraints aren't met.
type AddTransactionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddTransactionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddTransactionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddTransactionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddTransactionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddTransactionResponseValidationError) ErrorName() string {
	return "AddTransactionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AddTransactionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddTransactionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddTransactionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddTransactionResponseValidationError{}

// Validate checks the field values on PatchTransactionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PatchTransactionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PatchTransactionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PatchTransactionRequestMultiError, or nil if none found.
func (m *PatchTransactionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PatchTransactionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if m.Amount != nil {
		// no validation rules for Amount
	}

	if m.OccurredOn != nil {

		if all {
			switch v := interface{}(m.GetOccurredOn()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PatchTransactionRequestValidationError{
						field:  "OccurredOn",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PatchTransactionRequestValidationError{
						field:  "OccurredOn",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetOccurredOn()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PatchTransactionRequestValidationError{
					field:  "OccurredOn",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.CategoryId != nil {
		// no validation rules for CategoryId
	}

	if m.Description != nil {
		// no validation rules for Description
	}

	if len(errors) > 0 {
		return PatchTransactionRequestMultiError(errors)
	}

	return nil
}

// PatchTransactionRequestMultiError is an error wrapping multiple validation
// errors returned by PatchTransactionRequest.ValidateAll() if the designated
// constraints aren't met.
type PatchTransactionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PatchTransactionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PatchTransactionRequestMultiError) AllErrors() []error { return m }

// PatchTransactionRequestValidationError is the validation error returned by
// PatchTransactionRequest.Validate if the designated constraints aren't met.
type PatchTransactionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PatchTransactionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PatchTransactionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PatchTransactionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PatchTransactionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PatchTransactionRequestValidationError) ErrorName() string {
	return "PatchTransactionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PatchTransactionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPatchTransactionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PatchTransactionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PatchTransactionRequestValidationError{}

// Validate checks the field values on PatchTransactionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PatchTransactionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PatchTransactionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PatchTransactionResponseMultiError, or nil if none found.
func (m *PatchTransactionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PatchTransactionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PatchTransactionResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PatchTransactionResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PatchTransactionResponseValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PatchTransactionResponseMultiError(errors)
	}

	return nil
}

// PatchTransactionResponseMultiError is an error wrapping multiple validation
// errors returned by PatchTransactionResponse.ValidateAll() if the designated
// constraints aren't met.
type PatchTransactionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PatchTransactionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PatchTransactionResponseMultiError) AllErrors() []error { return m }

// PatchTransactionResponseValidationError is the validation error returned by
// PatchTransactionResponse.Validate if the designated constraints aren't met.
type PatchTransactionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PatchTransactionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PatchTransactionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PatchTransactionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PatchTransactionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PatchTransactionResponseValidationError) ErrorName() string {
	return "PatchTransactionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PatchTransactionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPatchTransactionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PatchTransactionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PatchTransactionResponseValidationError{}

// Validate checks the field values on DeleteTransactionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteTransactionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteTransactionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteTransactionRequestMultiError, or nil if none found.
func (m *DeleteTransactionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteTransactionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteTransactionRequestMultiError(errors)
	}

	return nil
}

// DeleteTransactionRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteTransactionRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteTransactionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteTransactionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteTransactionRequestMultiError) AllErrors() []error { return m }

// DeleteTransactionRequestValidationError is the validation error returned by
// DeleteTransactionRequest.Validate if the designated constraints aren't met.
type DeleteTransactionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteTransactionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteTransactionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteTransactionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteTransactionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteTransactionRequestValidationError) ErrorName() string {
	return "DeleteTransactionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteTransactionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteTransactionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteTransactionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteTransactionRequestValidationError{}

// Validate checks the field values on DeleteTransactionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteTransactionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteTransactionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteTransactionResponseMultiError, or nil if none found.
func (m *DeleteTransactionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteTransactionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteTransactionResponseMultiError(errors)
	}

	return nil
}

// DeleteTransactionResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteTransactionResponse.ValidateAll() if the
// designated constraints aren't met.
type DeleteTransactionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteTransactionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteTransactionResponseMultiError) AllErrors() []error { return m }

// DeleteTransactionResponseValidationError is the validation error returned by
// DeleteTransactionResponse.Validate if the designated constraints aren't met.
type DeleteTransactionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteTransactionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteTransactionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteTransactionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteTransactionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteTransactionResponseValidationError) ErrorName() string {
	return "DeleteTransactionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteTransactionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteTransactionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteTransactionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteTransactionResponseValidationError{}

// Validate checks the field values on AddBudgetRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddBudgetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddBudgetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddBudgetRequestMultiError, or nil if none found.
func (m *AddBudgetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddBudgetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPeriod()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AddBudgetRequestValidationError{
					field:  "Period",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AddBudgetRequestValidationError{
					field:  "Period",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPeriod()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AddBudgetRequestValidationError{
				field:  "Period",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CategoryId

	// no validation rules for Amount

	if len(errors) > 0 {
		return AddBudgetRequestMultiError(errors)
	}

	return nil
}

// AddBudgetRequestMultiError is an error wrapping multiple validation errors
// returned by AddBudgetRequest.ValidateAll() if the designated constraints
// aren't met.
type AddBudgetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddBudgetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddBudgetRequestMultiError) AllErrors() []error { return m }

// AddBudgetRequestValidationError is the validation error returned by
// AddBudgetRequest.Validate if the designated constraints aren't met.
type AddBudgetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddBudgetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddBudgetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddBudgetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddBudgetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddBudgetRequestValidationError) ErrorName() string { return "AddBudgetRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddBudgetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddBudgetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddBudgetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddBudgetRequestValidationError{}

// Validate checks the field values on AddBudgetResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddBudgetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddBudgetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddBudgetResponseMultiError, or nil if none found.
func (m *AddBudgetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddBudgetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AddBudgetResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AddBudgetResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AddBudgetResponseValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AddBudgetResponseMultiError(errors)
	}

	return nil
}

// AddBudgetResponseMultiError is an error wrapping multiple validation errors
// returned by AddBudgetResponse.ValidateAll() if the designated constraints
// aren't met.
type AddBudgetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddBudgetResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddBudgetResponseMultiError) AllErrors() []error { return m }

// AddBudgetResponseValidationError is the validation error returned by
// AddBudgetResponse.Validate if the designated constraints aren't met.
type AddBudgetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddBudgetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddBudgetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddBudgetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddBudgetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddBudgetResponseValidationError) ErrorName() string {
	return "AddBudgetResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AddBudgetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddBudgetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddBudgetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddBudgetResponseValidationError{}

// Validate checks the field values on PatchBudgetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PatchBudgetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PatchBudgetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PatchBudgetRequestMultiError, or nil if none found.
func (m *PatchBudgetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PatchBudgetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if m.Period != nil {

		if all {
			switch v := interface{}(m.GetPeriod()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PatchBudgetRequestValidationError{
						field:  "Period",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PatchBudgetRequestValidationError{
						field:  "Period",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPeriod()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PatchBudgetRequestValidationError{
					field:  "Period",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.CategoryId != nil {
		// no validation rules for CategoryId
	}

	if m.Amount != nil {
		// no validation rules for Amount
	}

	if len(errors) > 0 {
		return PatchBudgetRequestMultiError(errors)
	}

	return nil
}

// PatchBudgetRequestMultiError is an error wrapping multiple validation errors
// returned by PatchBudgetRequest.ValidateAll() if the designated constraints
// aren't met.
type PatchBudgetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PatchBudgetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PatchBudgetRequestMultiError) AllErrors() []error { return m }

// PatchBudgetRequestValidationError is the validation error returned by
// PatchBudgetRequest.Validate if the designated constraints aren't met.
type PatchBudgetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PatchBudgetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PatchBudgetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PatchBudgetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PatchBudgetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PatchBudgetRequestValidationError) ErrorName() string {
	return "PatchBudgetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PatchBudgetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPatchBudgetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PatchBudgetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PatchBudgetRequestValidationError{}

// Validate checks the field values on PatchBudgetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PatchBudgetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PatchBudgetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PatchBudgetResponseMultiError, or nil if none found.
func (m *PatchBudgetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PatchBudgetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PatchBudgetResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PatchBudgetResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PatchBudgetResponseValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PatchBudgetResponseMultiError(errors)
	}

	return nil
}

// PatchBudgetResponseMultiError is an error wrapping multiple validation
// errors returned by PatchBudgetResponse.ValidateAll() if the designated
// constraints aren't met.
type PatchBudgetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PatchBudgetResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PatchBudgetResponseMultiError) AllErrors() []error { return m }

// PatchBudgetResponseValidationError is the validation error returned by
// PatchBudgetResponse.Validate if the designated constraints aren't met.
type PatchBudgetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PatchBudgetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PatchBudgetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PatchBudgetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PatchBudgetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PatchBudgetResponseValidationError) ErrorName() string {
	return "PatchBudgetResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PatchBudgetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPatchBudgetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PatchBudgetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PatchBudgetResponseValidationError{}

// Validate checks the field values on DeleteBudgetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteBudgetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteBudgetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteBudgetRequestMultiError, or nil if none found.
func (m *DeleteBudgetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteBudgetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteBudgetRequestMultiError(errors)
	}

	return nil
}

// DeleteBudgetRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteBudgetRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteBudgetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteBudgetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteBudgetRequestMultiError) AllErrors() []error { return m }

// DeleteBudgetRequestValidationError is the validation error returned by
// DeleteBudgetRequest.Validate if the designated constraints aren't met.
type DeleteBudgetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteBudgetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteBudgetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteBudgetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteBudgetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteBudgetRequestValidationError) ErrorName() string {
	return "DeleteBudgetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteBudgetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteBudgetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteBudgetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteBudgetRequestValidationError{}

// Validate checks the field values on DeleteBudgetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteBudgetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteBudgetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteBudgetResponseMultiError, or nil if none found.
func (m *DeleteBudgetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteBudgetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeleteBudgetResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeleteBudgetResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeleteBudgetResponseValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DeleteBudgetResponseMultiError(errors)
	}

	return nil
}

// DeleteBudgetResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteBudgetResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteBudgetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteBudgetResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteBudgetResponseMultiError) AllErrors() []error { return m }

// DeleteBudgetResponseValidationError is the validation error returned by
// DeleteBudgetResponse.Validate if the designated constraints aren't met.
type DeleteBudgetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteBudgetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteBudgetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteBudgetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteBudgetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteBudgetResponseValidationError) ErrorName() string {
	return "DeleteBudgetResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteBudgetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteBudgetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteBudgetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteBudgetResponseValidationError{}
