// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ledger_service/service.proto

package ledger_servicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_ledger_service_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Date struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day           int32                  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Date) Reset() {
	*x = Date{}
	mi := &file_ledger_service_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{1}
}

func (x *Date) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Date) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *Date) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type DateMonth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateMonth) Reset() {
	*x = DateMonth{}
	mi := &file_ledger_service_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateMonth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateMonth) ProtoMessage() {}

func (x *DateMonth) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateMonth.ProtoReflect.Descriptor instead.
func (*DateMonth) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{2}
}

func (x *DateMonth) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *DateMonth) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	IsIncome      bool                   `protobuf:"varint,3,opt,name=is_income,json=isIncome,proto3" json:"is_income,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	OccurredOn    *Date                  `protobuf:"bytes,5,opt,name=occurred_on,json=occurredOn,proto3" json:"occurred_on,omitempty"`
	CategoryId    int64                  `protobuf:"varint,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_ledger_service_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{3}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Transaction) GetIsIncome() bool {
	if x != nil {
		return x.IsIncome
	}
	return false
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetOccurredOn() *Date {
	if x != nil {
		return x.OccurredOn
	}
	return nil
}

func (x *Transaction) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Budget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Period        *DateMonth             `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	CategoryId    int64                  `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_ledger_service_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{4}
}

func (x *Budget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Budget) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Budget) GetPeriod() *DateMonth {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *Budget) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Budget) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Budget) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Budget) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ReportItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Sum           *string                `protobuf:"bytes,2,opt,name=sum,proto3,oneof" json:"sum,omitempty"`
	SpentBudget   *string                `protobuf:"bytes,3,opt,name=spent_budget,json=spentBudget,proto3,oneof" json:"spent_budget,omitempty"`
	ItemBudget    *string                `protobuf:"bytes,4,opt,name=item_budget,json=itemBudget,proto3,oneof" json:"item_budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportItem) Reset() {
	*x = ReportItem{}
	mi := &file_ledger_service_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportItem) ProtoMessage() {}

func (x *ReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportItem.ProtoReflect.Descriptor instead.
func (*ReportItem) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReportItem) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ReportItem) GetSum() string {
	if x != nil && x.Sum != nil {
		return *x.Sum
	}
	return ""
}

func (x *ReportItem) GetSpentBudget() string {
	if x != nil && x.SpentBudget != nil {
		return *x.SpentBudget
	}
	return ""
}

func (x *ReportItem) GetItemBudget() string {
	if x != nil && x.ItemBudget != nil {
		return *x.ItemBudget
	}
	return ""
}

type PeriodReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeriodStart   *Date                  `protobuf:"bytes,1,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd     *Date                  `protobuf:"bytes,2,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	Items         []*ReportItem          `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodReport) Reset() {
	*x = PeriodReport{}
	mi := &file_ledger_service_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodReport) ProtoMessage() {}

func (x *PeriodReport) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodReport.ProtoReflect.Descriptor instead.
func (*PeriodReport) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{6}
}

func (x *PeriodReport) GetPeriodStart() *Date {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *PeriodReport) GetPeriodEnd() *Date {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *PeriodReport) GetItems() []*ReportItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_ledger_service_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{7}
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Category            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_ledger_service_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListCategoriesResponse) GetItems() []*Category {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListTransactionsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Limit                int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	FilterOccurredOnFrom *Date                  `protobuf:"bytes,3,opt,name=filter_occurred_on_from,json=filterOccurredOnFrom,proto3,oneof" json:"filter_occurred_on_from,omitempty"`
	FilterOccurredOnTo   *Date                  `protobuf:"bytes,4,opt,name=filter_occurred_on_to,json=filterOccurredOnTo,proto3,oneof" json:"filter_occurred_on_to,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_ledger_service_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTransactionsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTransactionsRequest) GetFilterOccurredOnFrom() *Date {
	if x != nil {
		return x.FilterOccurredOnFrom
	}
	return nil
}

func (x *ListTransactionsRequest) GetFilterOccurredOnTo() *Date {
	if x != nil {
		return x.FilterOccurredOnTo
	}
	return nil
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Transaction         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_ledger_service_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListTransactionsResponse) GetItems() []*Transaction {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListTransactionsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_ledger_service_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Transaction           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_ledger_service_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetTransactionResponse) GetItem() *Transaction {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsIncome      bool                   `protobuf:"varint,1,opt,name=is_income,json=isIncome,proto3" json:"is_income,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	OccurredOn    *Date                  `protobuf:"bytes,3,opt,name=occurred_on,json=occurredOn,proto3" json:"occurred_on,omitempty"`
	CategoryId    int64                  `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTransactionRequest) Reset() {
	*x = AddTransactionRequest{}
	mi := &file_ledger_service_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTransactionRequest) ProtoMessage() {}

func (x *AddTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTransactionRequest.ProtoReflect.Descriptor instead.
func (*AddTransactionRequest) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{13}
}

func (x *AddTransactionRequest) GetIsIncome() bool {
	if x != nil {
		return x.IsIncome
	}
	return false
}

func (x *AddTransactionRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *AddTransactionRequest) GetOccurredOn() *Date {
	if x != nil {
		return x.OccurredOn
	}
	return nil
}

func (x *AddTransactionRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *AddTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Transaction           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTransactionResponse) Reset() {
	*x = AddTransactionResponse{}
	mi := &file_ledger_service_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTransactionResponse) ProtoMessage() {}

func (x *AddTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTransactionResponse.ProtoReflect.Descriptor instead.
func (*AddTransactionResponse) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{14}
}

func (x *AddTransactionResponse) GetItem() *Transaction {
	if x != nil {
		return x.Item
	}
	return nil
}

type PatchTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        *string                `protobuf:"bytes,2,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	OccurredOn    *Date                  `protobuf:"bytes,3,opt,name=occurred_on,json=occurredOn,proto3,oneof" json:"occurred_on,omitempty"`
	CategoryId    *int64                 `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchTransactionRequest) Reset() {
	*x = PatchTransactionRequest{}
	mi := &file_ledger_service_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchTransactionRequest) ProtoMessage() {}

func (x *PatchTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchTransactionRequest.ProtoReflect.Descriptor instead.
func (*PatchTransactionRequest) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{15}
}

func (x *PatchTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatchTransactionRequest) GetAmount() string {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return ""
}

func (x *PatchTransactionRequest) GetOccurredOn() *Date {
	if x != nil {
		return x.OccurredOn
	}
	return nil
}

func (x *PatchTransactionRequest) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *PatchTransactionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type PatchTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Transaction           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchTransactionResponse) Reset() {
	*x = PatchTransactionResponse{}
	mi := &file_ledger_service_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchTransactionResponse) ProtoMessage() {}

func (x *PatchTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchTransactionResponse.ProtoReflect.Descriptor instead.
func (*PatchTransactionResponse) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{16}
}

func (x *PatchTransactionResponse) GetItem() *Transaction {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionRequest) Reset() {
	*x = DeleteTransactionRequest{}
	mi := &file_ledger_service_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionRequest) ProtoMessage() {}

func (x *DeleteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionResponse) Reset() {
	*x = DeleteTransactionResponse{}
	mi := &file_ledger_service_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionResponse) ProtoMessage() {}

func (x *DeleteTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionResponse.ProtoReflect.Descriptor instead.
func (*DeleteTransactionResponse) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{18}
}

type ListBudgetsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Limit            int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset           int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	FilterPeriodFrom *DateMonth             `protobuf:"bytes,3,opt,name=filter_period_from,json=filterPeriodFrom,proto3,oneof" json:"filter_period_from,omitempty"`
	FilterPeriodTo   *DateMonth             `protobuf:"bytes,4,opt,name=filter_period_to,json=filterPeriodTo,proto3,oneof" json:"filter_period_to,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListBudgetsRequest) Reset() {
	*x = ListBudgetsRequest{}
	mi := &file_ledger_service_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBudgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBudgetsRequest) ProtoMessage() {}

func (x *ListBudgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBudgetsRequest.ProtoReflect.Descriptor instead.
func (*ListBudgetsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListBudgetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBudgetsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListBudgetsRequest) GetFilterPeriodFrom() *DateMonth {
	if x != nil {
		return x.FilterPeriodFrom
	}
	return nil
}

func (x *ListBudgetsRequest) GetFilterPeriodTo() *DateMonth {
	if x != nil {
		return x.FilterPeriodTo
	}
	return nil
}

type ListBudgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Budget              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	HitCache      bool                   `protobuf:"varint,3,opt,name=hit_cache,json=hitCache,proto3" json:"hit_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBudgetsResponse) Reset() {
	*x = ListBudgetsResponse{}
	mi := &file_ledger_service_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBudgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBudgetsResponse) ProtoMessage() {}

func (x *ListBudgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBudgetsResponse.ProtoReflect.Descriptor instead.
func (*ListBudgetsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{20}
}

func (x *ListBudgetsResponse) GetItems() []*Budget {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListBudgetsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListBudgetsResponse) GetHitCache() bool {
	if x != nil {
		return x.HitCache
	}
	return false
}

type GetBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetRequest) Reset() {
	*x = GetBudgetRequest{}
	mi := &file_ledger_service_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetRequest) ProtoMessage() {}

func (x *GetBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetRequest.ProtoReflect.Descriptor instead.
func (*GetBudgetRequest) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetBudgetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBudgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Budget                `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	HitCache      bool                   `protobuf:"varint,2,opt,name=hit_cache,json=hitCache,proto3" json:"hit_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetResponse) Reset() {
	*x = GetBudgetResponse{}
	mi := &file_ledger_service_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetResponse) ProtoMessage() {}

func (x *GetBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetResponse.ProtoReflect.Descriptor instead.
func (*GetBudgetResponse) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetBudgetResponse) GetItem() *Budget {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetBudgetResponse) GetHitCache() bool {
	if x != nil {
		return x.HitCache
	}
	return false
}

type AddBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        *DateMonth             `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBudgetRequest) Reset() {
	*x = AddBudgetRequest{}
	mi := &file_ledger_service_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBudgetRequest) ProtoMessage() {}

func (x *AddBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBudgetRequest.ProtoReflect.Descriptor instead.
func (*AddBudgetRequest) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{23}
}

func (x *AddBudgetRequest) GetPeriod() *DateMonth {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *AddBudgetRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *AddBudgetRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type AddBudgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Budget                `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBudgetResponse) Reset() {
	*x = AddBudgetResponse{}
	mi := &file_ledger_service_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBudgetResponse) ProtoMessage() {}

func (x *AddBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBudgetResponse.ProtoReflect.Descriptor instead.
func (*AddBudgetResponse) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{24}
}

func (x *AddBudgetResponse) GetItem() *Budget {
	if x != nil {
		return x.Item
	}
	return nil
}

type PatchBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Period        *DateMonth             `protobuf:"bytes,2,opt,name=period,proto3,oneof" json:"period,omitempty"`
	CategoryId    *int64                 `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Amount        *string                `protobuf:"bytes,4,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchBudgetRequest) Reset() {
	*x = PatchBudgetRequest{}
	mi := &file_ledger_service_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchBudgetRequest) ProtoMessage() {}

func (x *PatchBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchBudgetRequest.ProtoReflect.Descriptor instead.
func (*PatchBudgetRequest) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{25}
}

func (x *PatchBudgetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatchBudgetRequest) GetPeriod() *DateMonth {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *PatchBudgetRequest) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *PatchBudgetRequest) GetAmount() string {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return ""
}

type PatchBudgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Budget                `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchBudgetResponse) Reset() {
	*x = PatchBudgetResponse{}
	mi := &file_ledger_service_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchBudgetResponse) ProtoMessage() {}

func (x *PatchBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchBudgetResponse.ProtoReflect.Descriptor instead.
func (*PatchBudgetResponse) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{26}
}

func (x *PatchBudgetResponse) GetItem() *Budget {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBudgetRequest) Reset() {
	*x = DeleteBudgetRequest{}
	mi := &file_ledger_service_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBudgetRequest) ProtoMessage() {}

func (x *DeleteBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBudgetRequest.ProtoReflect.Descriptor instead.
func (*DeleteBudgetRequest) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteBudgetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBudgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBudgetResponse) Reset() {
	*x = DeleteBudgetResponse{}
	mi := &file_ledger_service_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBudgetResponse) ProtoMessage() {}

func (x *DeleteBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBudgetResponse.ProtoReflect.Descriptor instead.
func (*DeleteBudgetResponse) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{28}
}

type ListReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateFrom      *Date                  `protobuf:"bytes,1,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        *Date                  `protobuf:"bytes,2,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsRequest) Reset() {
	*x = ListReportsRequest{}
	mi := &file_ledger_service_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsRequest) ProtoMessage() {}

func (x *ListReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsRequest.ProtoReflect.Descriptor instead.
func (*ListReportsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{29}
}

func (x *ListReportsRequest) GetDateFrom() *Date {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *ListReportsRequest) GetDateTo() *Date {
	if x != nil {
		return x.DateTo
	}
	return nil
}

type ListReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*PeriodReport        `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	HitCache      bool                   `protobuf:"varint,2,opt,name=hit_cache,json=hitCache,proto3" json:"hit_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsResponse) Reset() {
	*x = ListReportsResponse{}
	mi := &file_ledger_service_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsResponse) ProtoMessage() {}

func (x *ListReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsResponse.ProtoReflect.Descriptor instead.
func (*ListReportsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{30}
}

func (x *ListReportsResponse) GetReports() []*PeriodReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *ListReportsResponse) GetHitCache() bool {
	if x != nil {
		return x.HitCache
	}
	return false
}

type CSVExportTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	HitCache      bool                   `protobuf:"varint,3,opt,name=hit_cache,json=hitCache,proto3" json:"hit_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSVExportTransactionsResponse) Reset() {
	*x = CSVExportTransactionsResponse{}
	mi := &file_ledger_service_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSVExportTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSVExportTransactionsResponse) ProtoMessage() {}

func (x *CSVExportTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_service_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSVExportTransactionsResponse.ProtoReflect.Descriptor instead.
func (*CSVExportTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_service_service_proto_rawDescGZIP(), []int{31}
}

func (x *CSVExportTransactionsResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CSVExportTransactionsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CSVExportTransactionsResponse) GetHitCache() bool {
	if x != nil {
		return x.HitCache
	}
	return false
}

var File_ledger_service_service_proto protoreflect.FileDescriptor

const file_ledger_service_service_proto_rawDesc = "" +
	"\n" +
	"\x1cledger_service/service.proto\x12\x11ledger_service.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"B\n" +
	"\x04Date\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x01(\x05R\x03day\"5\n" +
	"\tDateMonth\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"\xe4\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1b\n" +
	"\tis_income\x18\x03 \x01(\bR\bisIncome\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x128\n" +
	"\voccurred_on\x18\x05 \x01(\v2\x17.ledger_service.v1.DateR\n" +
	"occurredOn\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\x03R\n" +
	"categoryId\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9c\x02\n" +
	"\x06Budget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x124\n" +
	"\x06period\x18\x03 \x01(\v2\x1c.ledger_service.v1.DateMonthR\x06period\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbb\x01\n" +
	"\n" +
	"ReportItem\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x15\n" +
	"\x03sum\x18\x02 \x01(\tH\x00R\x03sum\x88\x01\x01\x12&\n" +
	"\fspent_budget\x18\x03 \x01(\tH\x01R\vspentBudget\x88\x01\x01\x12$\n" +
	"\vitem_budget\x18\x04 \x01(\tH\x02R\n" +
	"itemBudget\x88\x01\x01B\x06\n" +
	"\x04_sumB\x0f\n" +
	"\r_spent_budgetB\x0e\n" +
	"\f_item_budget\"\xb7\x01\n" +
	"\fPeriodReport\x12:\n" +
	"\fperiod_start\x18\x01 \x01(\v2\x17.ledger_service.v1.DateR\vperiodStart\x126\n" +
	"\n" +
	"period_end\x18\x02 \x01(\v2\x17.ledger_service.v1.DateR\tperiodEnd\x123\n" +
	"\x05items\x18\x03 \x03(\v2\x1d.ledger_service.v1.ReportItemR\x05items\"\x17\n" +
	"\x15ListCategoriesRequest\"K\n" +
	"\x16ListCategoriesResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.ledger_service.v1.CategoryR\x05items\"\xa3\x02\n" +
	"\x17ListTransactionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12S\n" +
	"\x17filter_occurred_on_from\x18\x03 \x01(\v2\x17.ledger_service.v1.DateH\x00R\x14filterOccurredOnFrom\x88\x01\x01\x12O\n" +
	"\x15filter_occurred_on_to\x18\x04 \x01(\v2\x17.ledger_service.v1.DateH\x01R\x12filterOccurredOnTo\x88\x01\x01B\x1a\n" +
	"\x18_filter_occurred_on_fromB\x18\n" +
	"\x16_filter_occurred_on_to\"f\n" +
	"\x18ListTransactionsResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.ledger_service.v1.TransactionR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"'\n" +
	"\x15GetTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x16GetTransactionResponse\x122\n" +
	"\x04item\x18\x01 \x01(\v2\x1e.ledger_service.v1.TransactionR\x04item\"\xc9\x01\n" +
	"\x15AddTransactionRequest\x12\x1b\n" +
	"\tis_income\x18\x01 \x01(\bR\bisIncome\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x128\n" +
	"\voccurred_on\x18\x03 \x01(\v2\x17.ledger_service.v1.DateR\n" +
	"occurredOn\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"L\n" +
	"\x16AddTransactionResponse\x122\n" +
	"\x04item\x18\x01 \x01(\v2\x1e.ledger_service.v1.TransactionR\x04item\"\x8d\x02\n" +
	"\x17PatchTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\x06amount\x18\x02 \x01(\tH\x00R\x06amount\x88\x01\x01\x12=\n" +
	"\voccurred_on\x18\x03 \x01(\v2\x17.ledger_service.v1.DateH\x01R\n" +
	"occurredOn\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\x04 \x01(\x03H\x02R\n" +
	"categoryId\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01B\t\n" +
	"\a_amountB\x0e\n" +
	"\f_occurred_onB\x0e\n" +
	"\f_category_idB\x0e\n" +
	"\f_description\"N\n" +
	"\x18PatchTransactionResponse\x122\n" +
	"\x04item\x18\x01 \x01(\v2\x1e.ledger_service.v1.TransactionR\x04item\"*\n" +
	"\x18DeleteTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19DeleteTransactionResponse\"\x8c\x02\n" +
	"\x12ListBudgetsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12O\n" +
	"\x12filter_period_from\x18\x03 \x01(\v2\x1c.ledger_service.v1.DateMonthH\x00R\x10filterPeriodFrom\x88\x01\x01\x12K\n" +
	"\x10filter_period_to\x18\x04 \x01(\v2\x1c.ledger_service.v1.DateMonthH\x01R\x0efilterPeriodTo\x88\x01\x01B\x15\n" +
	"\x13_filter_period_fromB\x13\n" +
	"\x11_filter_period_to\"y\n" +
	"\x13ListBudgetsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.ledger_service.v1.BudgetR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1b\n" +
	"\thit_cache\x18\x03 \x01(\bR\bhitCache\"\"\n" +
	"\x10GetBudgetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"_\n" +
	"\x11GetBudgetResponse\x12-\n" +
	"\x04item\x18\x01 \x01(\v2\x19.ledger_service.v1.BudgetR\x04item\x12\x1b\n" +
	"\thit_cache\x18\x02 \x01(\bR\bhitCache\"\x81\x01\n" +
	"\x10AddBudgetRequest\x124\n" +
	"\x06period\x18\x01 \x01(\v2\x1c.ledger_service.v1.DateMonthR\x06period\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"B\n" +
	"\x11AddBudgetResponse\x12-\n" +
	"\x04item\x18\x01 \x01(\v2\x19.ledger_service.v1.BudgetR\x04item\"\xc8\x01\n" +
	"\x12PatchBudgetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\x06period\x18\x02 \x01(\v2\x1c.ledger_service.v1.DateMonthH\x00R\x06period\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\x03 \x01(\x03H\x01R\n" +
	"categoryId\x88\x01\x01\x12\x1b\n" +
	"\x06amount\x18\x04 \x01(\tH\x02R\x06amount\x88\x01\x01B\t\n" +
	"\a_periodB\x0e\n" +
	"\f_category_idB\t\n" +
	"\a_amount\"D\n" +
	"\x13PatchBudgetResponse\x12-\n" +
	"\x04item\x18\x01 \x01(\v2\x19.ledger_service.v1.BudgetR\x04item\"%\n" +
	"\x13DeleteBudgetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteBudgetResponse\"|\n" +
	"\x12ListReportsRequest\x124\n" +
	"\tdate_from\x18\x01 \x01(\v2\x17.ledger_service.v1.DateR\bdateFrom\x120\n" +
	"\adate_to\x18\x02 \x01(\v2\x17.ledger_service.v1.DateR\x06dateTo\"m\n" +
	"\x13ListReportsResponse\x129\n" +
	"\areports\x18\x01 \x03(\v2\x1f.ledger_service.v1.PeriodReportR\areports\x12\x1b\n" +
	"\thit_cache\x18\x02 \x01(\bR\bhitCache\"f\n" +
	"\x1dCSVExportTransactionsResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1b\n" +
	"\thit_cache\x18\x03 \x01(\bR\bhitCache2\xa9\n" +
	"\n" +
	"\x06Ledger\x12e\n" +
	"\x0eListCategories\x12(.ledger_service.v1.ListCategoriesRequest\x1a).ledger_service.v1.ListCategoriesResponse\x12k\n" +
	"\x10ListTransactions\x12*.ledger_service.v1.ListTransactionsRequest\x1a+.ledger_service.v1.ListTransactionsResponse\x12e\n" +
	"\x0eGetTransaction\x12(.ledger_service.v1.GetTransactionRequest\x1a).ledger_service.v1.GetTransactionResponse\x12e\n" +
	"\x0eAddTransaction\x12(.ledger_service.v1.AddTransactionRequest\x1a).ledger_service.v1.AddTransactionResponse\x12k\n" +
	"\x10PatchTransaction\x12*.ledger_service.v1.PatchTransactionRequest\x1a+.ledger_service.v1.PatchTransactionResponse\x12n\n" +
	"\x11DeleteTransaction\x12+.ledger_service.v1.DeleteTransactionRequest\x1a,.ledger_service.v1.DeleteTransactionResponse\x12\\\n" +
	"\vListBudgets\x12%.ledger_service.v1.ListBudgetsRequest\x1a&.ledger_service.v1.ListBudgetsResponse\x12V\n" +
	"\tGetBudget\x12#.ledger_service.v1.GetBudgetRequest\x1a$.ledger_service.v1.GetBudgetResponse\x12V\n" +
	"\tAddBudget\x12#.ledger_service.v1.AddBudgetRequest\x1a$.ledger_service.v1.AddBudgetResponse\x12\\\n" +
	"\vPatchBudget\x12%.ledger_service.v1.PatchBudgetRequest\x1a&.ledger_service.v1.PatchBudgetResponse\x12_\n" +
	"\fDeleteBudget\x12&.ledger_service.v1.DeleteBudgetRequest\x1a'.ledger_service.v1.DeleteBudgetResponse\x12\\\n" +
	"\vListReports\x12%.ledger_service.v1.ListReportsRequest\x1a&.ledger_service.v1.ListReportsResponse\x12u\n" +
	"\x15CSVExportTransactions\x12*.ledger_service.v1.ListTransactionsRequest\x1a0.ledger_service.v1.CSVExportTransactionsResponseB\xe4\x01\n" +
	"\x15com.ledger_service.v1B\fServiceProtoP\x01Z\\github.com/m11ano/budget_planner/backend/ledger/pkg/proto_pb/ledger_service;ledger_servicev1\xa2\x02\x03LXX\xaa\x02\x10LedgerService.V1\xca\x02\x10LedgerService\\V1\xe2\x02\x1cLedgerService\\V1\\GPBMetadata\xea\x02\x11LedgerService::V1b\x06proto3"

var (
	file_ledger_service_service_proto_rawDescOnce sync.Once
	file_ledger_service_service_proto_rawDescData []byte
)

func file_ledger_service_service_proto_rawDescGZIP() []byte {
	file_ledger_service_service_proto_rawDescOnce.Do(func() {
		file_ledger_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_service_service_proto_rawDesc), len(file_ledger_service_service_proto_rawDesc)))
	})
	return file_ledger_service_service_proto_rawDescData
}

var file_ledger_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_ledger_service_service_proto_goTypes = []any{
	(*Category)(nil),                      // 0: ledger_service.v1.Category
	(*Date)(nil),                          // 1: ledger_service.v1.Date
	(*DateMonth)(nil),                     // 2: ledger_service.v1.DateMonth
	(*Transaction)(nil),                   // 3: ledger_service.v1.Transaction
	(*Budget)(nil),                        // 4: ledger_service.v1.Budget
	(*ReportItem)(nil),                    // 5: ledger_service.v1.ReportItem
	(*PeriodReport)(nil),                  // 6: ledger_service.v1.PeriodReport
	(*ListCategoriesRequest)(nil),         // 7: ledger_service.v1.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),        // 8: ledger_service.v1.ListCategoriesResponse
	(*ListTransactionsRequest)(nil),       // 9: ledger_service.v1.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),      // 10: ledger_service.v1.ListTransactionsResponse
	(*GetTransactionRequest)(nil),         // 11: ledger_service.v1.GetTransactionRequest
	(*GetTransactionResponse)(nil),        // 12: ledger_service.v1.GetTransactionResponse
	(*AddTransactionRequest)(nil),         // 13: ledger_service.v1.AddTransactionRequest
	(*AddTransactionResponse)(nil),        // 14: ledger_service.v1.AddTransactionResponse
	(*PatchTransactionRequest)(nil),       // 15: ledger_service.v1.PatchTransactionRequest
	(*PatchTransactionResponse)(nil),      // 16: ledger_service.v1.PatchTransactionResponse
	(*DeleteTransactionRequest)(nil),      // 17: ledger_service.v1.DeleteTransactionRequest
	(*DeleteTransactionResponse)(nil),     // 18: ledger_service.v1.DeleteTransactionResponse
	(*ListBudgetsRequest)(nil),            // 19: ledger_service.v1.ListBudgetsRequest
	(*ListBudgetsResponse)(nil),           // 20: ledger_service.v1.ListBudgetsResponse
	(*GetBudgetRequest)(nil),              // 21: ledger_service.v1.GetBudgetRequest
	(*GetBudgetResponse)(nil),             // 22: ledger_service.v1.GetBudgetResponse
	(*AddBudgetRequest)(nil),              // 23: ledger_service.v1.AddBudgetRequest
	(*AddBudgetResponse)(nil),             // 24: ledger_service.v1.AddBudgetResponse
	(*PatchBudgetRequest)(nil),            // 25: ledger_service.v1.PatchBudgetRequest
	(*PatchBudgetResponse)(nil),           // 26: ledger_service.v1.PatchBudgetResponse
	(*DeleteBudgetRequest)(nil),           // 27: ledger_service.v1.DeleteBudgetRequest
	(*DeleteBudgetResponse)(nil),          // 28: ledger_service.v1.DeleteBudgetResponse
	(*ListReportsRequest)(nil),            // 29: ledger_service.v1.ListReportsRequest
	(*ListReportsResponse)(nil),           // 30: ledger_service.v1.ListReportsResponse
	(*CSVExportTransactionsResponse)(nil), // 31: ledger_service.v1.CSVExportTransactionsResponse
	(*timestamppb.Timestamp)(nil),         // 32: google.protobuf.Timestamp
}
var file_ledger_service_service_proto_depIdxs = []int32{
	1,  // 0: ledger_service.v1.Transaction.occurred_on:type_name -> ledger_service.v1.Date
	32, // 1: ledger_service.v1.Transaction.created_at:type_name -> google.protobuf.Timestamp
	32, // 2: ledger_service.v1.Transaction.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: ledger_service.v1.Budget.period:type_name -> ledger_service.v1.DateMonth
	32, // 4: ledger_service.v1.Budget.created_at:type_name -> google.protobuf.Timestamp
	32, // 5: ledger_service.v1.Budget.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 6: ledger_service.v1.PeriodReport.period_start:type_name -> ledger_service.v1.Date
	1,  // 7: ledger_service.v1.PeriodReport.period_end:type_name -> ledger_service.v1.Date
	5,  // 8: ledger_service.v1.PeriodReport.items:type_name -> ledger_service.v1.ReportItem
	0,  // 9: ledger_service.v1.ListCategoriesResponse.items:type_name -> ledger_service.v1.Category
	1,  // 10: ledger_service.v1.ListTransactionsRequest.filter_occurred_on_from:type_name -> ledger_service.v1.Date
	1,  // 11: ledger_service.v1.ListTransactionsRequest.filter_occurred_on_to:type_name -> ledger_service.v1.Date
	3,  // 12: ledger_service.v1.ListTransactionsResponse.items:type_name -> ledger_service.v1.Transaction
	3,  // 13: ledger_service.v1.GetTransactionResponse.item:type_name -> ledger_service.v1.Transaction
	1,  // 14: ledger_service.v1.AddTransactionRequest.occurred_on:type_name -> ledger_service.v1.Date
	3,  // 15: ledger_service.v1.AddTransactionResponse.item:type_name -> ledger_service.v1.Transaction
	1,  // 16: ledger_service.v1.PatchTransactionRequest.occurred_on:type_name -> ledger_service.v1.Date
	3,  // 17: ledger_service.v1.PatchTransactionResponse.item:type_name -> ledger_service.v1.Transaction
	2,  // 18: ledger_service.v1.ListBudgetsRequest.filter_period_from:type_name -> ledger_service.v1.DateMonth
	2,  // 19: ledger_service.v1.ListBudgetsRequest.filter_period_to:type_name -> ledger_service.v1.DateMonth
	4,  // 20: ledger_service.v1.ListBudgetsResponse.items:type_name -> ledger_service.v1.Budget
	4,  // 21: ledger_service.v1.GetBudgetResponse.item:type_name -> ledger_service.v1.Budget
	2,  // 22: ledger_service.v1.AddBudgetRequest.period:type_name -> ledger_service.v1.DateMonth
	4,  // 23: ledger_service.v1.AddBudgetResponse.item:type_name -> ledger_service.v1.Budget
	2,  // 24: ledger_service.v1.PatchBudgetRequest.period:type_name -> ledger_service.v1.DateMonth
	4,  // 25: ledger_service.v1.PatchBudgetResponse.item:type_name -> ledger_service.v1.Budget
	1,  // 26: ledger_service.v1.ListReportsRequest.date_from:type_name -> ledger_service.v1.Date
	1,  // 27: ledger_service.v1.ListReportsRequest.date_to:type_name -> ledger_service.v1.Date
	6,  // 28: ledger_service.v1.ListReportsResponse.reports:type_name -> ledger_service.v1.PeriodReport
	7,  // 29: ledger_service.v1.Ledger.ListCategories:input_type -> ledger_service.v1.ListCategoriesRequest
	9,  // 30: ledger_service.v1.Ledger.ListTransactions:input_type -> ledger_service.v1.ListTransactionsRequest
	11, // 31: ledger_service.v1.Ledger.GetTransaction:input_type -> ledger_service.v1.GetTransactionRequest
	13, // 32: ledger_service.v1.Ledger.AddTransaction:input_type -> ledger_service.v1.AddTransactionRequest
	15, // 33: ledger_service.v1.Ledger.PatchTransaction:input_type -> ledger_service.v1.PatchTransactionRequest
	17, // 34: ledger_service.v1.Ledger.DeleteTransaction:input_type -> ledger_service.v1.DeleteTransactionRequest
	19, // 35: ledger_service.v1.Ledger.ListBudgets:input_type -> ledger_service.v1.ListBudgetsRequest
	21, // 36: ledger_service.v1.Ledger.GetBudget:input_type -> ledger_service.v1.GetBudgetRequest
	23, // 37: ledger_service.v1.Ledger.AddBudget:input_type -> ledger_service.v1.AddBudgetRequest
	25, // 38: ledger_service.v1.Ledger.PatchBudget:input_type -> ledger_service.v1.PatchBudgetRequest
	27, // 39: ledger_service.v1.Ledger.DeleteBudget:input_type -> ledger_service.v1.DeleteBudgetRequest
	29, // 40: ledger_service.v1.Ledger.ListReports:input_type -> ledger_service.v1.ListReportsRequest
	9,  // 41: ledger_service.v1.Ledger.CSVExportTransactions:input_type -> ledger_service.v1.ListTransactionsRequest
	8,  // 42: ledger_service.v1.Ledger.ListCategories:output_type -> ledger_service.v1.ListCategoriesResponse
	10, // 43: ledger_service.v1.Ledger.ListTransactions:output_type -> ledger_service.v1.ListTransactionsResponse
	12, // 44: ledger_service.v1.Ledger.GetTransaction:output_type -> ledger_service.v1.GetTransactionResponse
	14, // 45: ledger_service.v1.Ledger.AddTransaction:output_type -> ledger_service.v1.AddTransactionResponse
	16, // 46: ledger_service.v1.Ledger.PatchTransaction:output_type -> ledger_service.v1.PatchTransactionResponse
	18, // 47: ledger_service.v1.Ledger.DeleteTransaction:output_type -> ledger_service.v1.DeleteTransactionResponse
	20, // 48: ledger_service.v1.Ledger.ListBudgets:output_type -> ledger_service.v1.ListBudgetsResponse
	22, // 49: ledger_service.v1.Ledger.GetBudget:output_type -> ledger_service.v1.GetBudgetResponse
	24, // 50: ledger_service.v1.Ledger.AddBudget:output_type -> ledger_service.v1.AddBudgetResponse
	26, // 51: ledger_service.v1.Ledger.PatchBudget:output_type -> ledger_service.v1.PatchBudgetResponse
	28, // 52: ledger_service.v1.Ledger.DeleteBudget:output_type -> ledger_service.v1.DeleteBudgetResponse
	30, // 53: ledger_service.v1.Ledger.ListReports:output_type -> ledger_service.v1.ListReportsResponse
	31, // 54: ledger_service.v1.Ledger.CSVExportTransactions:output_type -> ledger_service.v1.CSVExportTransactionsResponse
	42, // [42:55] is the sub-list for method output_type
	29, // [29:42] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_ledger_service_service_proto_init() }
func file_ledger_service_service_proto_init() {
	if File_ledger_service_service_proto != nil {
		return
	}
	file_ledger_service_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_ledger_service_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_ledger_service_service_proto_msgTypes[15].OneofWrappers = []any{}
	file_ledger_service_service_proto_msgTypes[19].OneofWrappers = []any{}
	file_ledger_service_service_proto_msgTypes[25].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_service_service_proto_rawDesc), len(file_ledger_service_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_service_service_proto_goTypes,
		DependencyIndexes: file_ledger_service_service_proto_depIdxs,
		MessageInfos:      file_ledger_service_service_proto_msgTypes,
	}.Build()
	File_ledger_service_service_proto = out.File
	file_ledger_service_service_proto_goTypes = nil
	file_ledger_service_service_proto_depIdxs = nil
}
